### ISSUE TITLE
Example Radioactive Decay (Numbers with uncertainties) not working in Julia 1.0

### ISSUE THREAD

**Issue by crstnbr** [JuliaDiffEq/DiffEqTutorials.jl#26] opened 2018-09-07 19:26 UTC
Source: http://nbviewer.jupyter.org/github/JuliaDiffEq/DiffEqTutorials.jl/blob/master/PhysicalModels/NumberUncertainties.ipynb

If I execute
```julia
# Half-life of radiocarbon, in thousands of years
c = 5.730 ± 0.040

#Setup
u₀ = 1 ± 0
tspan = (0 ± 0, 1 ± 0)

#Define the problem
radioactivedecay(u,p,t) = -c * u

#Pass to solver
prob = ODEProblem(radioactivedecay, u₀, tspan)
sol = solve(prob, Tsit5())
```
in Julia 1.0 I get:

```julia
MethodError: Measurement{Float64}(::Rational{Int64}) is ambiguous. Candidates:
  (::Type{Measurement{T}})(x::S) where {T, S} in Measurements at C:\Users\carsten\.julia\packages\Measurements\57KtG\src\Measurements.jl:61
  (::Type{T})(x::Rational{S}) where {S, T<:AbstractFloat} in Base at rational.jl:90
Possible fix, define
  (::Type{Measurement{T}})(::Rational{S})

Stacktrace:
 [1] #__init#203(::Int64, ::Array{Measurement{Float64},1}, ::Array{Measurement{Float64},1}, ::Array{Measurement{Float64},1}, ::Nothing, ::Bool, ::Nothing, ::Bool, ::Bool, ::Nothing, ::Bool, ::Bool, ::Measurement{Float64}, ::Bool, ::Rational{Int64}, ::Nothing, ::Nothing, ::Int64, ::Rational{Int64}, ::Int64, ::Int64, ::Rational{Int64}, ::Bool, ::Int64, ::Nothing, ::Nothing, ::Int64, ::Measurement{Float64}, ::Float64, ::typeof(DiffEqBase.ODE_DEFAULT_NORM), ::typeof(LinearAlgebra.opnorm), ::typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN), ::typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK), ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Int64, ::String, ::typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE), ::Nothing, ::Bool, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(DiffEqBase.__init), ::ODEProblem{Measurement{Float64},Tuple{Measurement{Float64},Measurement{Float64}},false,Nothing,ODEFunction{false,typeof(radioactivedecay),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem}, ::Tsit5, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at C:\Users\carsten\.julia\packages\OrdinaryDiffEq\nZPqS\src\solve.jl:80
 [2] __init(::ODEProblem{Measurement{Float64},Tuple{Measurement{Float64},Measurement{Float64}},false,Nothing,ODEFunction{false,typeof(radioactivedecay),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem}, ::Tsit5, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at C:\Users\carsten\.julia\packages\OrdinaryDiffEq\nZPqS\src\solve.jl:61
 [3] #__solve#202(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::ODEProblem{Measurement{Float64},Tuple{Measurement{Float64},Measurement{Float64}},false,Nothing,ODEFunction{false,typeof(radioactivedecay),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem}, ::Tsit5, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at C:\Users\carsten\.julia\packages\OrdinaryDiffEq\nZPqS\src\solve.jl:6
 [4] __solve(::ODEProblem{Measurement{Float64},Tuple{Measurement{Float64},Measurement{Float64}},false,Nothing,ODEFunction{false,typeof(radioactivedecay),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem}, ::Tsit5, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at C:\Users\carsten\.julia\packages\OrdinaryDiffEq\nZPqS\src\solve.jl:6 (repeats 5 times)
 [5] #solve#429(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::ODEProblem{Measurement{Float64},Tuple{Measurement{Float64},Measurement{Float64}},false,Nothing,ODEFunction{false,typeof(radioactivedecay),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem}, ::Tsit5) at C:\Users\carsten\.julia\packages\DiffEqBase\b3iNk\src\solve.jl:29
 [6] solve(::ODEProblem{Measurement{Float64},Tuple{Measurement{Float64},Measurement{Float64}},false,Nothing,ODEFunction{false,typeof(radioactivedecay),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem}, ::Tsit5) at C:\Users\carsten\.julia\packages\DiffEqBase\b3iNk\src\solve.jl:21
 [7] top-level scope at In[6]:13
```

**Comment by giordano** [comment] 2018-09-09 23:45
Can you please try again with latest version of `Measurements.jl` (v1.0.1)?  This has been most probably fixed by https://github.com/JuliaPhysics/Measurements.jl/pull/20

**Comment by crstnbr** [comment] 2018-09-10 22:31
Will do and report soon

**Comment by crstnbr** [comment] 2018-09-11 15:40
Doesn't work for Measurements v1.0.1.

**Comment by crstnbr** [comment] 2018-09-11 20:37
Doesn't work on Measurements#master. I get:

```julia
MethodError: no method matching OrdinaryDiffEq.Tsit5ConstantCache(::Measurement{Float64}, ::Measurement{Float64}, ::Measurement{Float64}, ::Measurement{BigFloat}, ::Measurement{Float64}, ::Measurement{Float64}, ::Measurement{Float64}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{Float64}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{Float64}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{Float64}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{Float64}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{BigFloat}, ::Measurement{Float64}, ::Measurement{Float64}, ::Measurement{Float64})
Closest candidates are:
  OrdinaryDiffEq.Tsit5ConstantCache(::T2, ::T2, ::T2, !Matched::T2, ::T2, ::T2, ::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, ::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, ::T, !Matched::T, !Matched::T, !Matched::T, ::T, !Matched::T, !Matched::T, ::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, !Matched::T, ::T, ::T, ::T) where {T, T2} at C:\Users\carsten\.julia\packages\OrdinaryDiffEq\OqDoB\src\tableaus\low_order_rk_tableaus.jl:498
```

**Comment by giordano** [comment] 2018-09-11 21:01
Ok, I've just installed IJulia in Julia 0.7 and I get the same error as the last one about `OrdinaryDiffEq.Tsit5ConstantCache`

**Comment by crstnbr** [comment] 2018-09-11 21:31
@ChrisRackauckas, any idea?

**Comment by ChrisRackauckas** [comment] 2018-09-13 20:47
It looks like `T(number)` doesn't always return a number of type `T` for Measurements anymore.

```julia
typeof(Measurement{Float64}(big".9800255409045096857298102862870245954942137979563024768854764293221195950761080302604")) == Measurement{BigFloat})
```

is an MWE.

**Comment by ChrisRackauckas** [comment] 2018-09-13 20:49
A proper fix might be to use

```julia
convert(Measurement{Float64},big".9800255409045096857298102862870245954942137979563024768854764293221195950761080302604")
``` 

instead. That would need to be done for every constant in any of the tableaus: 

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/tree/master/src/tableaus
https://github.com/JuliaDiffEq/StochasticDiffEq.jl/blob/master/src/tableaus.jl
https://github.com/JuliaDiffEq/DiffEqDevTools.jl/blob/master/src/ode_tableaus.jl

If anyone has a good regex for this it would be a quick but substantially sized PR. (@YingboMa ?)

**Comment by giordano** [comment] 2018-09-13 20:53
I guess that I could also fix that one in `Measurements.jl`

**Comment by giordano** [comment] 2018-09-13 21:09
Ok, I've fixed this issue with https://github.com/JuliaPhysics/Measurements.jl/pull/24, but the tutorial still fails at the first cell with:
```
MethodError: no method matching Float64(::Measurement{Float64})
Closest candidates are:
  Float64(::Real, !Matched::RoundingMode) where T<:AbstractFloat at rounding.jl:173
  Float64(::T<:Number) where T<:Number at boot.jl:725
  Float64(!Matched::Int8) at float.jl:60
  ...

Stacktrace:
 [1] Float64(::Measurement{Float64}) at ./deprecated.jl:468
 [2] ode_determine_initdt(::Measurement{Float64}, ::Float64, ::Float64, ::Float64, ::Measurement{Float64}, ::Measurement{Float64}, ::typeof(DiffEqBase.ODE_DEFAULT_NORM), ::ODEProblem{Measurement{Float64},Tuple{Float64,Float64},false,Nothing,ODEFunction{false,typeof(radioactivedecay),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem}, ::OrdinaryDiffEq.ODEIntegrator{Tsit5,Measurement{Float64},Float64,Nothing,Float64,Float64,Float64,Array{Measurement{Float64},1},ODESolution{Measurement{Float64},1,Array{Measurement{Float64},1},Nothing,Nothing,Array{Float64,1},Array{Array{Measurement{Float64},1},1},ODEProblem{Measurement{Float64},Tuple{Float64,Float64},false,Nothing,ODEFunction{false,typeof(radioactivedecay),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{false,typeof(radioactivedecay),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Measurement{Float64},1},Array{Float64,1},Array{Array{Measurement{Float64},1},1},OrdinaryDiffEq.Tsit5ConstantCache{Measurement{Float64},Float64}}},ODEFunction{false,typeof(radioactivedecay),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.Tsit5ConstantCache{Measurement{Float64},Float64},OrdinaryDiffEq.DEOptions{Measurement{Float64},Measurement{Float64},Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(LinearAlgebra.opnorm),CallbackSet{Tuple{},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.LessThan},DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Nothing,Nothing,Int64,Array{Float64,1},Array{Float64,1},Array{Float64,1}},Measurement{Float64}}) at /home/mose/.julia/packages/OrdinaryDiffEq/OqDoB/src/initdt.jl:138
 [3] auto_dt_reset!(::OrdinaryDiffEq.ODEIntegrator{Tsit5,Measurement{Float64},Float64,Nothing,Float64,Float64,Float64,Array{Measurement{Float64},1},ODESolution{Measurement{Float64},1,Array{Measurement{Float64},1},Nothing,Nothing,Array{Float64,1},Array{Array{Measurement{Float64},1},1},ODEProblem{Measurement{Float64},Tuple{Float64,Float64},false,Nothing,ODEFunction{false,typeof(radioactivedecay),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{false,typeof(radioactivedecay),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Measurement{Float64},1},Array{Float64,1},Array{Array{Measurement{Float64},1},1},OrdinaryDiffEq.Tsit5ConstantCache{Measurement{Float64},Float64}}},ODEFunction{false,typeof(radioactivedecay),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.Tsit5ConstantCache{Measurement{Float64},Float64},OrdinaryDiffEq.DEOptions{Measurement{Float64},Measurement{Float64},Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(LinearAlgebra.opnorm),CallbackSet{Tuple{},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.LessThan},DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Nothing,Nothing,Int64,Array{Float64,1},Array{Float64,1},Array{Float64,1}},Measurement{Float64}}) at /home/mose/.julia/packages/OrdinaryDiffEq/OqDoB/src/integrators/integrator_interface.jl:250
 [4] #__init#203(::Int64, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Nothing, ::Bool, ::Nothing, ::Bool, ::Bool, ::Nothing, ::Bool, ::Bool, ::Float64, ::Bool, ::Rational{Int64}, ::Nothing, ::Nothing, ::Int64, ::Rational{Int64}, ::Int64, ::Int64, ::Rational{Int64}, ::Bool, ::Int64, ::Nothing, ::Nothing, ::Int64, ::Float64, ::Float64, ::typeof(DiffEqBase.ODE_DEFAULT_NORM), ::typeof(LinearAlgebra.opnorm), ::typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN), ::typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK), ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Int64, ::String, ::typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE), ::Nothing, ::Bool, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(DiffEqBase.__init), ::ODEProblem{Measurement{Float64},Tuple{Float64,Float64},false,Nothing,ODEFunction{false,typeof(radioactivedecay),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem}, ::Tsit5, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at /home/mose/.julia/packages/OrdinaryDiffEq/OqDoB/src/solve.jl:220
 [5] __init(::ODEProblem{Measurement{Float64},Tuple{Float64,Float64},false,Nothing,ODEFunction{false,typeof(radioactivedecay),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem}, ::Tsit5, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at /home/mose/.julia/packages/OrdinaryDiffEq/OqDoB/src/solve.jl:61
 [6] #__solve#202(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::ODEProblem{Measurement{Float64},Tuple{Float64,Float64},false,Nothing,ODEFunction{false,typeof(radioactivedecay),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem}, ::Tsit5, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at /home/mose/.julia/packages/OrdinaryDiffEq/OqDoB/src/solve.jl:6
 [7] __solve at /home/mose/.julia/packages/OrdinaryDiffEq/OqDoB/src/solve.jl:6 [inlined] (repeats 3 times)
 [8] #solve#428(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::ODEProblem{Measurement{Float64},Tuple{Float64,Float64},false,Nothing,ODEFunction{false,typeof(radioactivedecay),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem}, ::Tsit5) at /home/mose/.julia/packages/DiffEqBase/mKOqQ/src/solve.jl:19
 [9] solve(::ODEProblem{Measurement{Float64},Tuple{Float64,Float64},false,Nothing,ODEFunction{false,typeof(radioactivedecay),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem}, ::Tsit5) at /home/mose/.julia/packages/DiffEqBase/mKOqQ/src/solve.jl:15
 [10] top-level scope at In[1]:14
```

I didn't define the conversion `Measurement` → `Float64` on purpose

**Comment by ChrisRackauckas** [comment] 2018-09-13 21:18
If you give a starting `dt` it should work then. The issue is

```julia
  if d₀ < 1//10^(5) || d₁ < 1//10^(5)
    dt₀ = _tType(1//10^(6))
  else
    dt₀ = _tType((d₀/d₁)/100)
  end
```

should give a zero uncertainty dt0 estimate. For units this works fine because d0 and d1 are two different estimates and the units cancel and then they are re-applied. Maybe we can multiply by `oneunit(_tType)`.

**Comment by ChrisRackauckas** [comment] 2018-09-13 21:19
For reference it's here: https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/initdt.jl#L135-L139 . Is the conversion fix live?

**Comment by giordano** [comment] 2018-09-13 21:35
> Is the conversion fix live?

Yes, the PR has been merged, you can find it if you check out `master`

**Comment by ChrisRackauckas** [comment] 2018-09-22 10:53
Fixed on master branches.

**Closed by ChrisRackauckas** 2018-09-22 10:53 UTC
