### ISSUE TITLE
Still issues with DiffEq + Unitful

### ISSUE THREAD

**Issue by crstnbr** [JuliaDiffEq/DiffEqTutorials.jl#30] opened 2018-09-27 17:43 UTC
Related to https://github.com/JuliaDiffEq/DiffEqTutorials.jl/issues/29.

The [unitful example](https://nbviewer.jupyter.org/github/JuliaDiffEq/DiffEqTutorials.jl/blob/master/ExtraODEFeatures/Unit%20Checked%20Arithmetic%20via%20Unitful.ipynb) in the notebooks now works. However this maybe slightly advanced example does not.

```julia
using DifferentialEquations
import Unitful: s, m, kg, N

# coordinate: u = [position, momentum]
# parameters: p = [mass, force constanst]
function f_harmonic!(du,u,p,t)
  du[1] = u[2]/p[1]
  du[2] = -p[2]/p[1]*u[1]
end

mass = 1.0kg
k = 1.0N/m
p = [mass, k]

u0 = [1.0m, 0.0kg*m/s] # initial values (position, momentum)

tspan = (0.0s, 10.0s)

prob = ODEProblem(f_harmonic!, u0, tspan, p)

sol = solve(prob)
```

Running this I get

```julia
MethodError: no method matching Quantity{Float64,D,U} where U where D(::Int64)
Closest candidates are:
  Quantity{Float64,D,U} where U where D(::T<:Number) where T<:Number at boot.jl:725
  Quantity{Float64,D,U} where U where D(!Matched::Base.TwicePrecision) where T<:Number at twiceprecision.jl:243
  Quantity{Float64,D,U} where U where D(!Matched::AbstractChar) where T<:Union{AbstractChar, Number} at char.jl:50
```

**Comment by ChrisRackauckas** [comment] 2018-09-28 20:53
Duplicate of https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/352 . We might be able to fix it but it'll take work. Tracking it there since it's not just a tutorial issue.

**Closed by ChrisRackauckas** 2018-09-28 20:53 UTC
