### ISSUE TITLE
Tutorial - Heat Equation Finite Element Method

### ISSUE THREAD

**Issue by MLackner** [JuliaDiffEq/DiffEqTutorials.jl#14] opened 2017-11-07 13:21 UTC
Hi,

the code in [the heat equation tutorial](http://docs.juliadiffeq.org/stable/tutorials/femheat_example.html) gives the following error for me:

```julia
using DifferentialEquations

f(t,x,u)  = ones(size(x,1)) - .5u
u0_func(x) = zeros(size(x,1))

tspan = (0.0,1.0)
dx = 1//2^(3)
dt = 1//2^(7)

mesh = parabolic_squaremesh([0 1 0 1],dx,dt,tspan,:neumann)
u0 = u0_func(mesh.node)
prob = HeatProblem(u0,f,mesh)

sol = solve(prob,FEMDiffEqHeatImplicitEuler())
```

```julia
Error displaying DiffEqPDEBase.FEMSolution{Float64,2,Array{Array{Float64,1},1},Void,Dict{Symbol,Float64},Array{Float64,1},DiffEqPDEBase.HeatProblem{false,false,DiffEqPDEBase.FEMMesh{Array{Rational{Int64},2},Array{Float64,1},Rational{Int64},Tuple{Float64,Float64}},#f,Void,DiffEqPDEBase.##21#30,DiffEqPDEBase.##22#31,Array{Float64,1},DiffEqPDEBase.##14#23,Void,Float64}}: type FEMSolution has no field retcode
show at solution_interface.jl:34 [inlined]
(::LastMain.Juno.##1#2{DiffEqPDEBase.FEMSolution{Float64,2,Array{Array{Float64,1},1},Void,Dict{Symbol,Float64},Array{Float64,1},DiffEqPDEBase.HeatProblem{false,false,DiffEqPDEBase.FEMMesh{Array{Rational{Int64},2},Array{Float64,1},Rational{Int64},Tuple{Float64,Float64}},#f,Void,DiffEqPDEBase.##21#30,DiffEqPDEBase.##22#31,Array{Float64,1},DiffEqPDEBase.##14#23,Void,Float64}}})(::Base.AbstractIOBuffer{Array{UInt8,1}}) at types.jl:11
#sprint#228(::Void, ::Function, ::Int64, ::Function) at io.jl:66
Type at types.jl:51 [inlined]
Type at types.jl:52 [inlined]
render(::LastMain.Juno.Editor, ::DiffEqPDEBase.FEMSolution{Float64,2,Array{Array{Float64,1},1},Void,Dict{Symbol,Float64},Array{Float64,1},DiffEqPDEBase.HeatProblem{false,false,DiffEqPDEBase.FEMMesh{Array{Rational{Int64},2},Array{Float64,1},Rational{Int64},Tuple{Float64,Float64}},#f,Void,DiffEqPDEBase.##21#30,DiffEqPDEBase.##22#31,Array{Float64,1},DiffEqPDEBase.##14#23,Void,Float64}}) at types.jl:13
render′(::LastMain.Juno.Editor, ::DiffEqPDEBase.FEMSolution{Float64,2,Array{Array{Float64,1},1},Void,Dict{Symbol,Float64},Array{Float64,1},DiffEqPDEBase.HeatProblem{false,false,DiffEqPDEBase.FEMMesh{Array{Rational{Int64},2},Array{Float64,1},Rational{Int64},Tuple{Float64,Float64}},#f,Void,DiffEqPDEBase.##21#30,DiffEqPDEBase.##22#31,Array{Float64,1},DiffEqPDEBase.##14#23,Void,Float64}}) at errors.jl:106
(::LastMain.Atom.##50#54{String})() at eval.jl:57
macro expansion at eval.jl:53 [inlined]
(::LastMain.Atom.##48#52{Dict{String,Any}})() at task.jl:80
```

Running Julia v0.6.1 with DifferentialEquations v3.0.2

**Comment by ChrisRackauckas** [comment] 2017-11-07 13:24
Oh, this needs an update after the 3.0 display change. It still works, but the display is broken. Thanks for the issue.

**Comment by MLackner** [comment] 2017-11-07 13:26
Is there a documentation about the display change, so I can fix my code?

**Comment by ChrisRackauckas** [comment] 2017-11-07 13:39
I don't immediately see what the fix is, since the `display` should internally be calling these:

https://github.com/JuliaDiffEq/DiffEqPDEBase.jl/blob/master/src/solutions.jl#L35

instead of these:

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/solutions/solution_interface.jl#L24

since `FEMSolution <: AbstractFEMSolution <: AbstractTimeseriesSolution`, but something is going wrong there.

Does this also happen in the REPL? Or is thus Juno-specific?

**Comment by MLackner** [comment] 2017-11-07 13:46
Ah... this works in the REPL

However when using a Jupyter Notebook I get a similar error:

```julia
type FEMSolution has no field retcode

Stacktrace:
 [1] show at /Users/lackner/.julia/v0.6/DiffEqBase/src/solutions/solution_interface.jl:34 [inlined]
 [2] limitstringmime(::MIME{Symbol("text/plain")}, ::DiffEqPDEBase.FEMSolution{Float64,2,Array{Array{Float64,1},1},Void,Dict{Symbol,Float64},Array{Float64,1},DiffEqPDEBase.HeatProblem{false,false,DiffEqPDEBase.FEMMesh{Array{Rational{Int64},2},Array{Float64,1},Rational{Int64},Tuple{Float64,Float64}},#f,Void,DiffEqPDEBase.##21#30,DiffEqPDEBase.##22#31,Array{Float64,1},DiffEqPDEBase.##14#23,Void,Float64}}) at /Users/lackner/.julia/v0.6/IJulia/src/inline.jl:24
 [3] display_dict(::DiffEqPDEBase.FEMSolution{Float64,2,Array{Array{Float64,1},1},Void,Dict{Symbol,Float64},Array{Float64,1},DiffEqPDEBase.HeatProblem{false,false,DiffEqPDEBase.FEMMesh{Array{Rational{Int64},2},Array{Float64,1},Rational{Int64},Tuple{Float64,Float64}},#f,Void,DiffEqPDEBase.##21#30,DiffEqPDEBase.##22#31,Array{Float64,1},DiffEqPDEBase.##14#23,Void,Float64}}) at /Users/lackner/.julia/v0.6/IJulia/src/execute_request.jl:27
 [4] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /Users/lackner/.julia/v0.6/IJulia/src/execute_request.jl:182
 [5] eventloop(::ZMQ.Socket) at /Users/lackner/.julia/v0.6/IJulia/src/eventloop.jl:8
 [6] (::IJulia.##14#17)() at ./task.jl:335
```

**Comment by ChrisRackauckas** [comment] 2017-11-07 14:01
What's your `Pkg.status()`? Are you on the newest version of DiffEqPDEBase.jl?

**Comment by MLackner** [comment] 2017-11-07 14:12
Oh sorry forget the src/solutions.jl is missing. I was looking in DiffEqBase instead of DiffEqPDEBase.

I removed and all DiffEq* Packages and added DifferntialEquations again but the error persists.

Here are the versions that are installed:

```
 - DiffBase                      0.2.0
 - DiffEqBase                    2.3.1
 - DiffEqBiological              0.3.0
 - DiffEqCallbacks               0.4.0
 - DiffEqDevTools                0.9.5
 - DiffEqDiffTools               0.0.2
 - DiffEqFinancial               0.3.0
 - DiffEqJump                    0.5.1
 - DiffEqMonteCarlo              0.9.1
 - DiffEqNoiseProcess            0.6.0
 - DiffEqPDEBase                 0.3.4
 - DiffEqParamEstim              0.7.1
 - DiffEqPhysics                 0.0.1
 - DiffEqSensitivity             0.3.0
 - DiffEqUncertainty             0.0.1
```

**Comment by ChrisRackauckas** [comment] 2017-11-07 14:29
Hmm, I don't know what to say but it's clearly a versioning issue.

<img width="743" alt="capture" src="https://user-images.githubusercontent.com/1814174/32498530-c3b19cd0-c384-11e7-89bb-cfcf7fedf1b8.PNG">

<img width="728" alt="capture2" src="https://user-images.githubusercontent.com/1814174/32498585-f15c1a48-c384-11e7-8dec-fe9cdc03321e.PNG">

But all of your packages look up to date?

**Comment by MLackner** [comment] 2017-11-07 15:13
I wiped everything and reinstalled Atom and DifferentialEquations. Still get the error.
`Pkg.status()` gives this now:

```
2 required packages:
 - Atom                          0.6.2
 - DifferentialEquations         3.0.2

103 additional packages:
 - AlgebraicDiffEq               0.1.0
 - BandedMatrices                0.3.0
 - BinDeps                       0.7.0
 - Blink                         0.5.4
 - BoundaryValueDiffEq           0.1.0
 - Calculus                      0.2.2
 - ChunkedArrays                 0.1.1
 - CodeTools                     0.4.7
 - Codecs                        0.4.0
 - Combinatorics                 0.4.1
 - CommonSubexpressions          0.0.1
 - Compat                        0.34.0
 - Conda                         0.7.0
 - DataStructures                0.7.2
 - DelayDiffEq                   1.5.0
 - DiffBase                      0.2.0
 - DiffEqBase                    2.3.1
 - DiffEqBiological              0.3.0
 - DiffEqCallbacks               0.4.0
 - DiffEqDevTools                0.9.5
 - DiffEqDiffTools               0.0.2
 - DiffEqFinancial               0.3.0
 - DiffEqJump                    0.5.1
 - DiffEqMonteCarlo              0.9.1
 - DiffEqNoiseProcess            0.6.0
 - DiffEqPDEBase                 0.3.4
 - DiffEqParamEstim              0.7.1
 - DiffEqPhysics                 0.0.1
 - DiffEqSensitivity             0.3.0
 - DiffEqUncertainty             0.0.1
 - DimensionalPlotRecipes        0.0.2
 - Distances                     0.5.0
 - DistributedArrays             0.4.0
 - Distributions                 0.15.0
 - DocSeeker                     0.1.0
 - EllipsisNotation              0.3.0
 - FiniteElementDiffEq           0.4.0
 - ForwardDiff                   0.5.0
 - FunctionWrappers              0.1.0
 - GenericSVD                    0.1.0
 - Hiccup                        0.1.1
 - Homebrew                      0.6.0
 - HttpCommon                    0.3.0
 - HttpParser                    0.3.0
 - HttpServer                    0.2.0
 - IterTools                     0.1.0
 - IterativeSolvers              0.4.1
 - JSON                          0.15.2
 - Juno                          0.3.1
 - LNR                           0.0.2
 - Lazy                          0.12.0
 - LearnBase                     0.1.6
 - LineSearches                  3.1.0
 - LinearMaps                    1.0.3
 - LossFunctions                 0.2.0
 - LsqFit                        0.3.0
 - MacroTools                    0.4.0
 - MbedTLS                       0.5.1
 - Media                         0.3.0
 - MuladdMacro                   0.0.2
 - MultiScaleArrays              0.4.0
 - Mustache                      0.3.0
 - Mux                           0.2.3
 - NLSolversBase                 3.1.0
 - NLsolve                       0.12.1
 - NaNMath                       0.2.6
 - Optim                         0.10.1
 - OptimBase                     0.1.0
 - OrdinaryDiffEq                2.24.0
 - PDMats                        0.7.1
 - ParameterizedFunctions        2.3.0
 - Parameters                    0.8.0
 - PenaltyFunctions              0.0.2
 - Polynomials                   0.1.6
 - PositiveFactorizations        0.1.0
 - Primes                        0.2.0
 - QuadGK                        0.1.3
 - RandomNumbers                 0.1.0
 - RealInterface                 0.0.3
 - RecipesBase                   0.2.3
 - RecursiveArrayTools           0.12.4
 - Reexport                      0.0.3
 - Requires                      0.4.3
 - ResettableStacks              0.2.0
 - Rmath                         0.3.0
 - Roots                         0.4.1
 - SHA                           0.5.2
 - SimpleTraits                  0.5.1
 - SpecialFunctions              0.3.4
 - StaticArrays                  0.6.4
 - StatsBase                     0.19.0
 - StatsFuns                     0.5.0
 - SteadyStateDiffEq             0.1.0
 - StochasticDiffEq              2.15.0
 - StringDistances               0.2.0
 - SugarBLAS                     0.0.4
 - Sundials                      0.14.2
 - SymEngine                     0.2.0
 - Tokenize                      0.4.2
 - URIParser                     0.2.0
 - UnicodePlots                  0.2.5
 - VectorizedRoutines            0.0.2
 - WebSockets                    0.3.0
```

**Comment by ChrisRackauckas** [comment] 2017-11-07 15:21
Weird... I cannot reproduce this at all. Maybe someone like @pfitzseb can chime in about something that might be going on with the `display` mechanism?

**Comment by ChrisRackauckas** [comment] 2017-11-08 16:31
The issue was a missing tag... I did the display fixes awhile back but didn't realize I forgot to tag them.

https://github.com/JuliaLang/METADATA.jl/pull/11919

**Comment by ChrisRackauckas** [comment] 2017-11-08 16:43
The tag has been merged and if you `Pkg.update()` it display properly now. Sorry that took so long to track down!

**Closed by ChrisRackauckas** 2017-11-08 16:43 UTC
